parameters:
#    foot_pronostic.example.class: Foot\PronosticBundle\Example

services:
#    foot_pronostic.example:
#        class: %foot_pronostic.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
