<?php

namespace Foot\PronosticBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PronostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PronostRepository extends EntityRepository
{
}
