<?php

namespace Foot\PronosticBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TeamsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeamsRepository extends EntityRepository
{
}
